const route = require('express').Router()
const StudentController = require('../controllers/Student')
const TeacherController = require('../controllers/Teacher')
const getScore = require('../middlewares/getScore')
const checkTokenRegisterStudent = require('../middlewares/checkTokenRegisterStudent')

route.post("/register/:token",  checkTokenRegisterStudent, StudentController.register)
route.post("/login", StudentController.login)
route.get("/lessons/:TeacherId", StudentController.getLessons)
route.get("/courses/:LessonId", StudentController.getCourse)
route.get("/quiz/:CourseId", StudentController.getQuiz)
route.get("/questions/:QuizId", StudentController.getQuestion)
route.get("/scores/:StudentId", StudentController.getScore)
route.post("/answer/:QuestionId", getScore, StudentController.answer)
route.get("/student/:id", StudentController.getStudent)

route.post("/teacher/register", TeacherController.teacherRegister)
route.post("/teacher/login", TeacherController.teacherLogin)
route.post("/teacher/lesson/:teacherId", TeacherController.createLesson)
route.post("/teacher/course/:lessonId", TeacherController.createCourse)
route.post("/teacher/quiz/:CourseId", TeacherController.createQuiz)
route.post("/teacher/question/:QuizId", TeacherController.createQuestion)
route.delete("/teacher/question/:questionId", TeacherController.deleteQuiz)
route.get("/teacher/student-list/:TeacherId", TeacherController.showStudent)
route.get("/teacher/course", TeacherController.getCourse)
route.get("/teacher/quiz", TeacherController.getQuiz)

module.exports = route